import SvgBase from "@svg/svg.base";
import SeatModel from "@model/seat.model";
import Seats from "../block-item.seats.index";
import { SeatItemCircle } from "./seat-item.circle";
import { CoordinateModel } from "@model/coordinate.model";
import { SeatItemTitle } from "./seat-item.title";
import { SeatAction } from "@enum/global";
import { SeatItemCheck } from "./seat-item.check";
import { SeatItemCustomSvg } from "@svg/stage/blocks/block-item/seat/seat-item.custom";
export declare class SeatItem extends SvgBase {
    parent: Seats;
    item: SeatModel;
    circle: SeatItemCircle;
    seatCustomSvg: SeatItemCustomSvg;
    title: SeatItemTitle;
    coordinates: CoordinateModel;
    check: SeatItemCheck;
    constructor(parent: Seats, item: SeatModel, seatCustomSvg: any);
    setColor(color: string, animation?: boolean): this;
    updateColor(color?: string | null): this;
    select(color?: string | null): this;
    unSelect(): this;
    isSelected(): Boolean;
    isSalable(): Boolean;
    hover(): void;
    blur(): void;
    getColor(action?: SeatAction | null): string;
    update(): this;
    afterGenerate(): void;
}
