/*
 * $project.fileName
 * https://github.com/seatmap/canvas Copyright 2018 Ali Sait TEKE
 */

enum BLOCK_EVENT {

}


export enum EventType {
    ADD_BLOCK = "BLOCK.ADD",
    REMOVE_BLOCK = "BLOCK.REMOVE",
    CLICK_BLOCK = "BLOCK.CLICK",
    MOUSEENTER_BLOCK = "BLOCK.MOUSEENTER",
    MOUSEMOVE_BLOCK = "BLOCK.MOUSEMOVE",
    MOUSELEAVE_BLOCK = "BLOCK.MOUSELEAVE",
    UPDATE_BLOCK = "BLOCK.UPDATE",
    CLICK_SEAT = "SEAT.CLICK",
    ADD_SEAT = "SEAT.ADD",
    REMOVE_SEAT = "SEAT.REMOVE",
    ZOOM_LEVEL_CHANGE = "ZOOM_LEVEL_CHANGE",
    BOUND_CLICK = "BOUND.CLICK",

    MOUSE_MOVE = "MOUSE.MOVE",

    RESIZE_WINDOW = "WINDOW.RESIZE",

    CLICK_ZOOMOUT = "ZOOM-OUT-BG.CLICK",
    MOUSEMOVE_ZOOMOUT = "ZOOM-OUT-BG.MOUSEMOVE",
}

export enum ZoomLevel {
    VENUE = "VENUE",
    BLOCK = "BLOCK",
    SEAT = "SEAT"
}